[package]
name = "e2b_connect"
version = "0.1.0"
edition = "2021"
description = "E2B Connect RPC client for Rust"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tokio = { workspace = true }
http = "1.0"
# Connect RPC dependencies
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures = { workspace = true }
tracing = { workspace = true }
base64 = "0.22"

[build-dependencies]
tonic-build = { version = "0.12", default-features = false, features = ["prost", "cleanup-markdown"] }
